### ISSUE TITLE
Compilation failed due to check function after apt versioned package installation.

### ISSUE THREAD

**Issue by takryo00** [GoogleCloudPlatform/osconfig#360]
## Summary
Compilation failed due to check function to update resource state after installation does not check the version of installed package.
If we configured to install specific version package, compilation failed all time.

## Cause
The check function use installed package information from package manager by parse function. The parse function is implemented to take the information of version too, but the check function does not use the version information to check after installation it on completed.

### check function
https://github.com/GoogleCloudPlatform/osconfig/blob/cefab268a965676bcfa9a93189c25db41b0aed24/config/package_resource.go#L308-L310

### parse function
https://github.com/GoogleCloudPlatform/osconfig/blob/cefab268a965676bcfa9a93189c25db41b0aed24/packages/apt_deb.go#L304

### package cache use only "package name"
https://github.com/GoogleCloudPlatform/osconfig/blob/cefab268a965676bcfa9a93189c25db41b0aed24/config/package_resource.go#L268-L271

## Reproduction of failure
1. create GCE instance with ubuntu 20.04 LT.
2. create OS Policy with configuration to install version specific nginx.
3. compilation failed all time.

```
id: setup-version-specified-nginx
mode: ENFORCEMENT
resourceGroups:
  - osFilter:
      osShortName: ubuntu
    resources:
      - id: install-pkg
        pkg:
          desiredState: INSTALLED
          apt:
            name: "nginx=1.18.0-0ubuntu1.2"
```
