### ISSUE TITLE
Attempting to install package Config_apply_task.go fails on line 223

### ISSUE THREAD

**Issue by dbergman24** [GoogleCloudPlatform/osconfig#452]
I'm trying to enforce installation datadog agent using os config policies. I'm getting this error (edited to important bits). 

```
Enforce state: resource "datadog-install-linux" error: unexpected return code from enforce: 0, stdout: [34m
* Datadog Agent 7 install script v1.11.0
[0m
[34m
* Installing YUM sources for Datadog
[0m
[34m* Installing the Datadog Agent package
[0m
C...     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 31875  100 31875    0     0  73173      0 --:--:-- --:--:-- --:--:-- 73275
```

severity: "ERROR"
sourceLocation: {
file: "config_task.go"
function: "github.com/GoogleCloudPlatform/osconfig/agentendpoint.enforceConfigResourceState"
line: "223"
}

Here's the yaml - check if its already running or else install:

```
id: datadog-install-linux
mode: ENFORCEMENT
resourceGroups:
  - resources:
      id: datadog-install-linux
      exec:
        validate:
          interpreter: SHELL
          script: if sudo systemctl --quiet datadog-agent; then exit 100; else exit 101; fi
        enforce:
          interpreter: SHELL
          script: sudo DD_API_KEY=<apikeyhere> DD_SITE="datadoghq.com" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)"
```
